language: python
python:
  - "3.3"
  - "3.4"

# command to install dependencies
install:
  - ./scripts/support/setup.sh

# command to run tests
script:
  - make build

notifications:
  email:
    on_success: change
    on_failure: always